"""Drift guard: the README coverage matrix must match the live corpus.

The coverage section in README.md is generated by scripts/coverage.py. This test
regenerates it and fails if README.md is stale -- so adding a vector without
running `python scripts/coverage.py --write` is caught in CI, not in review.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Load scripts/coverage.py by path so it cannot collide with the 'coverage'
# pip package (pytest --cov imports that one first).
_spec = importlib.util.spec_from_file_location("_subvectors_coverage", ROOT / "scripts" / "coverage.py")
coverage = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(coverage)


def _norm(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n").strip("\n")


def test_readme_coverage_section_matches_corpus() -> None:
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    start, end = coverage.MARKER_START, coverage.MARKER_END
    assert start in readme and end in readme, "README.md is missing the COVERAGE markers"
    between = readme.split(start, 1)[1].split(end, 1)[0]
    section = start + between + end
    assert _norm(section) == _norm(coverage.render_section()), (
        "README.md coverage section is stale; run `python scripts/coverage.py --write`"
    )
