#!/usr/bin/env python3
"""Generate the corpus coverage matrix embedded in README.md.

The corpus is the product, so its shape -- which issuer x consumer pairs are
covered, and how the judgments grade out -- should be legible at a glance and
never drift from the vectors. This script is the single source of truth for that
section; ``tests/test_readme_coverage.py`` fails if README.md is out of sync.

Usage:
    python scripts/coverage.py            # print the generated section to stdout
    python scripts/coverage.py --write    # rewrite the section in README.md in place
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
VECTORS_DIR = REPO_ROOT / "vectors"
README = REPO_ROOT / "README.md"

MARKER_START = "<!-- COVERAGE:START (generated by scripts/coverage.py -- run `python scripts/coverage.py --write`) -->"
MARKER_END = "<!-- COVERAGE:END -->"

# Column order for the matrix: AWS operators, the composite, then Azure and GCP.
CONSUMERS = [
    "aws-stringlike",
    "aws-stringequals",
    "aws-all",
    "azure-fic-exact",
    "azure-fic-flexible",
    "gcp-cel",
]
# Preferred issuer row order; any issuer not listed is appended alphabetically.
ISSUER_ORDER = ["github", "gitlab", "bitbucket", "circleci", "terraform-cloud"]
GRADES = ["safe", "caution", "dangerous"]


def _load_suites() -> list[dict]:
    suites = []
    for path in sorted(VECTORS_DIR.glob("*.json")):
        suites.append(json.loads(path.read_text(encoding="utf-8")))
    return suites


def _issuer_sort_key(issuer: str) -> tuple[int, str]:
    return (ISSUER_ORDER.index(issuer), "") if issuer in ISSUER_ORDER else (len(ISSUER_ORDER), issuer)


def render_body() -> str:
    suites = _load_suites()
    vectors = [(s["suite"], v) for s in suites for v in s["vectors"]]

    matrix: Counter[tuple[str, str]] = Counter()
    issuers: set[str] = set()
    grades: Counter[str] = Counter()
    ungraded = 0
    for _suite, v in vectors:
        issuer = v["issuer"]
        consumer = v["condition"]["consumer"]
        issuers.add(issuer)
        matrix[(issuer, consumer)] += 1
        judgment = v.get("judgment")
        if judgment:
            grades[judgment["grade"]] += 1
        else:
            ungraded += 1

    issuer_rows = sorted(issuers, key=_issuer_sort_key)
    total_vectors = len(vectors)

    lines: list[str] = []
    lines.append(
        f"**{len(suites)} suites - {total_vectors} vectors** across {len(issuer_rows)} "
        f"issuers and {len({c for (_i, c) in matrix})} consumer semantics."
    )
    lines.append("")
    lines.append("Vectors by issuer x cloud-consumer semantics:")
    lines.append("")
    header = ["Issuer", *CONSUMERS, "Total"]
    lines.append("| " + " | ".join(header) + " |")
    lines.append("| " + " | ".join(["---"] * len(header)) + " |")
    col_totals: Counter[str] = Counter()
    for issuer in issuer_rows:
        cells = [f"`{issuer}`"]
        row_total = 0
        for consumer in CONSUMERS:
            n = matrix[(issuer, consumer)]
            col_totals[consumer] += n
            row_total += n
            cells.append(str(n) if n else "-")
        cells.append(f"**{row_total}**")
        lines.append("| " + " | ".join(cells) + " |")
    total_cells = ["**Total**"]
    for consumer in CONSUMERS:
        total_cells.append(f"**{col_totals[consumer]}**" if col_totals[consumer] else "-")
    total_cells.append(f"**{total_vectors}**")
    lines.append("| " + " | ".join(total_cells) + " |")

    lines.append("")
    lines.append("Suites:")
    lines.append("")
    for s in suites:
        n = len(s["vectors"])
        lines.append(f"- `{s['suite']}` {s['version']} - {n} vector{'s' if n != 1 else ''}")

    lines.append("")
    graded_bits = " - ".join(f"{grades[g]} {g}" for g in GRADES)
    lines.append(
        f"Judgments: {graded_bits} - {ungraded} ungraded "
        f"(mechanical no-match / contrast vectors carry no safety grade)."
    )
    return "\n".join(lines)


def render_section() -> str:
    return f"{MARKER_START}\n\n{render_body()}\n\n{MARKER_END}"


def write() -> None:
    text = README.read_text(encoding="utf-8")
    if MARKER_START not in text or MARKER_END not in text:
        raise SystemExit(
            "README.md has no COVERAGE markers; add the START/END comment markers first."
        )
    before = text.split(MARKER_START)[0]
    after = text.split(MARKER_END, 1)[1]
    README.write_text(before + render_section() + after, encoding="utf-8")


if __name__ == "__main__":
    if "--write" in sys.argv[1:]:
        write()
        print("[+] README.md coverage section updated")
    else:
        print(render_section())
